In [50]:
import torch
import dgl

In [63]:
graphs, _ = dgl.load_graphs('/afs/inf.ed.ac.uk/user/s20/s2041332/mlp_project/graph/dev_graphs_demo.dgl')
g = graphs[2]
g.ndata['e_id']

tensor([2, 2, 0, 1, 0, 0, 0, 0, 2], dtype=torch.int32)

In [5]:
import torch

a = torch.tensor([[1,2,3], [4,5,6]])
torch.cat((a[0], a[1]), dim=-1)

tensor([1, 2, 3, 4, 5, 6])

In [6]:
a.max(dim=1).values

tensor([3, 6])

In [41]:
max_nodes = 10
bs = 2

node_num_batch = torch.tensor([1,2])
node_num_batch = node_num_batch.unsqueeze(-1)

a = torch.arange(max_nodes,dtype=torch.int).unsqueeze(0)
print(a)

mask = a.repeat((bs, 1)) < node_num_batch
print(mask.float())

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]], dtype=torch.int32)
tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0., 0., 0., 0., 0., 0.]])


RuntimeError: Could not run 'aten::_sparse_softmax' with arguments from the 'CPU' backend. 'aten::_sparse_softmax' is only available for these backends: [SparseCPU, SparseCUDA, BackendSelect, Named, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, Tracer, Autocast, Batched, VmapMode].

SparseCPU: registered at /pytorch/build/aten/src/ATen/SparseCPUType.cpp:239 [kernel]
SparseCUDA: registered at /pytorch/build/aten/src/ATen/SparseCUDAType.cpp:320 [kernel]
BackendSelect: fallthrough registered at /pytorch/aten/src/ATen/core/BackendSelectFallbackKernel.cpp:3 [backend fallback]
Named: registered at /pytorch/aten/src/ATen/core/NamedRegistrations.cpp:7 [backend fallback]
AutogradOther: registered at /pytorch/torch/csrc/autograd/generated/VariableType_4.cpp:7586 [autograd kernel]
AutogradCPU: registered at /pytorch/torch/csrc/autograd/generated/VariableType_4.cpp:7586 [autograd kernel]
AutogradCUDA: registered at /pytorch/torch/csrc/autograd/generated/VariableType_4.cpp:7586 [autograd kernel]
AutogradXLA: registered at /pytorch/torch/csrc/autograd/generated/VariableType_4.cpp:7586 [autograd kernel]
AutogradPrivateUse1: registered at /pytorch/torch/csrc/autograd/generated/VariableType_4.cpp:7586 [autograd kernel]
AutogradPrivateUse2: registered at /pytorch/torch/csrc/autograd/generated/VariableType_4.cpp:7586 [autograd kernel]
AutogradPrivateUse3: registered at /pytorch/torch/csrc/autograd/generated/VariableType_4.cpp:7586 [autograd kernel]
Tracer: registered at /pytorch/torch/csrc/autograd/generated/TraceType_4.cpp:9291 [kernel]
Autocast: fallthrough registered at /pytorch/aten/src/ATen/autocast_mode.cpp:254 [backend fallback]
Batched: registered at /pytorch/aten/src/ATen/BatchingRegistrations.cpp:511 [backend fallback]
VmapMode: fallthrough registered at /pytorch/aten/src/ATen/VmapModeRegistrations.cpp:33 [backend fallback]


In [47]:
import numpy as np

nodes_candidates_id = 1
num_candidate = 4
num_of_answer_in_graph = 3
max_candidates = 10

np.array([np.pad(np.array([i == np.array(d['nodes_candidates_id']) for i in range(len(d['candidates']))]),
                                   ((0, max_candidates - len(d['candidates'])),
                                    (0, max_nodes - len(d['nodes_candidates_id']))), mode='constant')
                            for d in data_mb])

np.array([np.pad(np.array([i == np.array(nodes_candidates_id) for i in range(num_candidate)]),
                 ((0, 10-4),(0, 500-3)), mode='constant')])


ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (2,2) and requested shape (1,2)